In [ ]:
# NUMPY:
# a powerful library to work with numbers and matrices

In [5]:
import numpy  # RUN THIS SECTION FIRST

In [6]:
# creating numpy arrays(matrices):

# 1D
arr = numpy.array([1, 2, 3])
print(arr)
print()

# 2D
arr = numpy.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8 ,9]
])
print(arr)
print()

# zero or one initializations
arr = numpy.zeros((4, 5))
print(arr)
print()

arr = numpy.ones((1, 3))
print(arr)
print()

[1 2 3]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[1. 1. 1.]]



In [7]:
# identity matrix
m = numpy.identity(3)
print(m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [46]:
# getting array dimentions
m = numpy.array([
    [1, 2, 3],
    [4, 5 ,6]
])
print(m.shape)

(2, 3)


In [64]:
# operations on matrices:

# +, -
m1 = numpy.array([
    [1, 2, 3],
    [4, 5 ,6]
])
m2 = numpy.array([
    [-1, -2, -3],
    [-4, -5 ,-6]
])

print(m1 + m2)
print()

# scalar multiplication
print(2 * m1)
print()

# matrix dot product
m1 = numpy.array([
    [1, 2, 3],
    [4, 5, 6]
])
m2 = numpy.array([
    [1, 1],
    [1, 1],
    [1, 1]
])
print(numpy.dot(m1, m2))
print()

[[0 0 0]
 [0 0 0]]

[[ 2  4  6]
 [ 8 10 12]]

[[ 6  6]
 [15 15]]



In [ ]:
# indexing
m = numpy.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8 ,9]
])

print(m[1, 2])  # or m[1][2]
print()

In [98]:
# slicing:

m = numpy.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8 ,9]
])

# slicing rows [0, 2) and columns [1, 3) 
m1 = m[0: 2, 1: 3]
print(m1)
print()

# slicing last column
m2 = m[:, 2]
print(m2)
print()

# slicing all columns except the last one
m3 = m[:, 0: -1]
print(m3)

[[2 3]
 [5 6]]

[3 6 9]

[[1 2]
 [4 5]
 [7 8]]


In [103]:
# reshaping
m = numpy.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8 ,9]
])        
c = m[:, 2]
print(c)
print()
                
c = c.reshape((3, 1))
print(c)

[3 6 9]

[[3]
 [6]
 [9]]


In [104]:
# combining
A = numpy.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

b = numpy.array([
    [7],
    [8],
    [9]
])

print(numpy.hstack((A, b)))

[[1 2 7]
 [3 4 8]
 [5 6 9]]
